"""Plugin-related application ports."""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class PluginPort(Protocol):
    @property
    def name(self) -> str: ...

    @property
    def description(self) -> str: ...

    async def execute(self, **kwargs) -> Any: ...

    def get_schema(self) -> Dict[str, Any]: ...

    def get_metadata(self) -> Dict[str, Any]: ...


class PluginManagerPort(Protocol):
    def list_plugins(self) -> List[Dict[str, Any]]: ...

    def get_plugin_schemas(self) -> Dict[str, Dict[str, Any]]: ...

    def has_plugin(self, plugin_name: str) -> bool: ...

    def get_plugin(self, plugin_name: str) -> Optional[PluginPort]: ...
